### ISSUE TITLE
SQLiteDatabaseLockedException thrown from

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/message-counter#28]
Google Play Console reporting the below Exceptions.

`android.database.sqlite.SQLiteDatabaseLockedException: 
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java:0)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1112)
  at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:823)
  at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:509)
  at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:483)
  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:382)
  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
  at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
  at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:888)
  at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:858)
  at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:695)
  at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1159)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
  at com.ae.apps.common.db.DataBaseHelper.<init>(DataBaseHelper.java:0)
  at com.ae.apps.messagecounter.db.CounterDataBaseAdapter.<init>(CounterDataBaseAdapter.java:0)
  at com.ae.apps.messagecounter.managers.SentCountDataManager.getSentCountData(SentCountDataManager.java:0)
  at <OR>.checkForUnLoggedMessages(SentCountDataManager.java:0)
  at com.ae.apps.messagecounter.fragments.SentCountFragment.showSentCountDetails(SentCountFragment.java:0)
  at com.ae.apps.messagecounter.fragments.SentCountFragment.updateLayout(SentCountFragment.java:0)
  at com.ae.apps.messagecounter.fragments.SentCountFragment.access$300(SentCountFragment.java:0)
  at com.ae.apps.messagecounter.fragments.SentCountFragment$1$1.run(SentCountFragment.java:0)`

Key location from stacktrace:

**at com.ae.apps.messagecounter.managers.SentCountDataManager.getSentCountData(SentCountDataManager.java:0)
  at OR.checkForUnLoggedMessages(SentCountDataManager.java:0)**

**Comment by midhunhk** [comment]
The `CommonUtils.isFirstInstall(mContext)` would return true only for fresh installations, where `checkForUnLoggedMessages()` would be invoked and access the CounterDataBase in a new thread.

Solutions:
- [ ] Reproduce this issue on a fresh install
- [ ] Convert SentCountDataManager as a Singleton?
- [ ] Close the counterDataBase in finally block of `checkForUnLoggedMessages()`
- [ ] Add a delay before invoking `checkForUnLoggedMessages()` so that db is closed in `getSentCountData`
- [ ] Restructure `SentCountFragment `

**Comment by midhunhk** [comment]
Unable to reproduce the issue with a fresh install. Added a couple of solutions for improvement. Since this is a silent error, we would push with next release and monitor for any further issues.
