### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/message-counter#29]
Google Play Console reporting with below stack trace.

`java.lang.NullPointerException: 
  at com.ae.apps.common.managers.ContactManager.getContactIdFromAddress(ContactManager.java:0)
  at com.ae.apps.messagecounter.utils.MessageCounterUtils.sortThisMap(MessageCounterUtils.java:0)
  at <OR>.getMessageCountDegrees(MessageCounterUtils.java:0)
  at <OR>.getContactMessageList(MessageCounterUtils.java:0)
  at <OR>.convertAddressToContact(MessageCounterUtils.java:0)
  at <OR>.getIndexFromDate(MessageCounterUtils.java:0)
  at <OR>.getWeekStartDate(MessageCounterUtils.java:0)
  at <OR>.getMessageLimitValue(MessageCounterUtils.java:0)
  at <OR>.getCycleSentCount(MessageCounterUtils.java:0)
  at com.ae.apps.messagecounter.activities.MainActivity$1.run(MainActivity.java:0)
  at java.lang.Thread.run(Thread.java:818)`

**Comment by midhunhk** [comment]
Reported for LG Devices. Could this be device specific? We don't have any recent changes in the reported area.

**Comment by midhunhk** [comment]
Only reference to `ContactManager.getContactIdFromAddress()` is from below line.
https://github.com/midhunhk/message-counter/blob/master/messageCounter/src/main/java/com/ae/apps/messagecounter/utils/MessageCounterUtils.java#L196

**Comment by midhunhk** [comment]
This should be fixed based on the latest code in AeAppsLib as well as MessageCounter
