### ISSUE TITLE
IabHelper IllegalStateException

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/message-counter#33]
`java.lang.IllegalStateException: 
  at com.ae.apps.common.utils.inapp.IabHelper.flagStartAsync(IabHelper.java:0)
  at <OR>.flagEndAsync(IabHelper.java:0)
  at com.ae.apps.common.utils.inapp.IabHelper.enableDebugLogging(IabHelper.java:0)
  at <OR>.startSetup(IabHelper.java:0)
  at <OR>.dispose(IabHelper.java:0)
  at <OR>.launchPurchaseFlow(IabHelper.java:0)
  at <OR>.launchPurchaseFlow(IabHelper.java:0)
  at <OR>.handleActivityResult(IabHelper.java:0)
  at <OR>.consume(IabHelper.java:0)
  at <OR>.consumeAsync(IabHelper.java:0)
  at <OR>.getResponseDesc(IabHelper.java:0)
  at <OR>.checkSetupDone(IabHelper.java:0)
  at <OR>.getResponseCodeFromBundle(IabHelper.java:0)
  at <OR>.getResponseCodeFromIntent(IabHelper.java:0)
  at <OR>.consumeAsyncInternal(IabHelper.java:0)
  at com.ae.apps.common.utils.inapp.IabHelper.enableDebugLogging(IabHelper.java:0)
  at <OR>.startSetup(IabHelper.java:0)
  at <OR>.dispose(IabHelper.java:0)
  at <OR>.launchPurchaseFlow(IabHelper.java:0)
  at <OR>.launchPurchaseFlow(IabHelper.java:0)
  at <OR>.handleActivityResult(IabHelper.java:0)
  at <OR>.consume(IabHelper.java:0)
  at <OR>.consumeAsync(IabHelper.java:0)
  at <OR>.getResponseDesc(IabHelper.java:0)
  at <OR>.checkSetupDone(IabHelper.java:0)
  at <OR>.getResponseCodeFromBundle(IabHelper.java:0)
  at <OR>.getResponseCodeFromIntent(IabHelper.java:0)
  at <OR>.consumeAsyncInternal(IabHelper.java:0)
  at com.ae.apps.common.activities.DonationsBaseActivity.launchPurchaseFlow(DonationsBaseActivity.java:0)
  at <OR>.processPurchase(DonationsBaseActivity.java:0)
  at <OR>.checkPurchaseResponse(DonationsBaseActivity.java:0)
  at <OR>.onPurchaseConsumeFinished(DonationsBaseActivity.java:0)
  at <OR>.access$000(DonationsBaseActivity.java:0)
  at <OR>.access$100(DonationsBaseActivity.java:0)
  at <OR>.access$200(DonationsBaseActivity.java:0)
  at com.ae.apps.messagecounter.activities.DonationsActivity.checkPurchaseResponse(DonationsActivity.java:0)
  at <OR>.onPurchaseConsumeFinished(DonationsActivity.java:0)
  at <OR>.access$000(DonationsActivity.java:0)
  at com.ae.apps.messagecounter.activities.DonationsActivity$1.onClick(DonationsActivity.java:0)
  at android.view.View.performClick(View.java:5721)
  at android.widget.TextView.performClick(TextView.java:10949)
  at android.view.View$PerformClick.run(View.java:22624)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:7407)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by midhunhk** [comment]
https://stackoverflow.com/questions/26185808/current-android-iab-reference
https://stackoverflow.com/questions/15066095/illegalstateexception-in-iab-v3
https://stackoverflow.com/questions/15575605/android-in-app-billing-cant-start-async-operation-because-another-async-operat

**Comment by midhunhk** [comment]
IabHelper.java is present in LibAeApps project

**Comment by midhunhk** [comment]
This seems to be implemented as per specification. May be caused by clicking multiple times on the purchase button. Will reopen and investigate if more instances are reported.
