### ISSUE TITLE
Application Crashes when pressing Menu button on LG Device

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/message-counter#6]
A user has reported the following app crash log.

java.lang.NullPointerException
at com.android.internal.policy.impl.PhoneWindow.onKeyUpPanel(PhoneWindow.java:1004)
at com.android.internal.policy.impl.PhoneWindow.onKeyUp(PhoneWindow.java:1712)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2125)
at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3611)
at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3581)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2831)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4929)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
at dalvik.system.NativeStart.main(Native Method)

**Comment by midhunhk** [comment]
This is an issue with LGE firmware as mentioned in the below links.

http://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC29190703
http://stackoverflow.com/questions/26833242/nullpointerexception-phonewindowonkeyuppanel1002-main

Since this is not a severe issue (only affects LGE users and if they press hardware menu key), this fix will be provided based on the above links in the next release.

**Comment by midhunhk** [comment]
added code fix for this issue
